# https://aka.ms/yaml

trigger:
- master

variables:
  - name: CakeVersion
    value: '0.34.1'
  - name: CakeToolPath
    value: 'dotnet-cake-tool-0-34-1'
  - group: SopiSecrets

pool:
  vmImage: 'ubuntu-latest'

steps:

- pwsh: if (!(Test-Path -Path ${{ variables.CakeToolPath }})) { dotnet tool install Cake.Tool --tool-path ${{ variables.CakeToolPath }} --version ${{ variables.CakeVersion }} }
  displayName: 'Install cake tool'
  workingDirectory: 'tools'

- task: Bash@3
  displayName: Bootstrap Cake
  inputs:
    targetType: inline
    script: exec ./tools/${{ variables.CakeToolPath }}/dotnet-cake build.cake --bootstrap

- task: Bash@3
  displayName: Run Cake Target
  inputs:
    targetType: inline
    script: exec ./tools/${{ variables.CakeToolPath }}/dotnet-cake build.cake --target="PackAndPublish"
  env:
    NUGET_API_KEY: $(NuGetApiKey)
    MYGET_API_KEY: $(MyGetApiKey)
  
- task: CopyFiles@2
  inputs:
    sourceFolder: 'artifacts'
    contents: '**/**' 
    targetFolder: $(Build.ArtifactStagingDirectory) 

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop' 
    targetPath: $(Build.ArtifactStagingDirectory)
